### ISSUE TITLE
Support VPC lookup by name rather than by VPC ID

### ISSUE THREAD

**Issue by evanjtravis** [techservicesillinois/terraform-aws-client-server-security-group#1]
This module could be made to look up the ID from a supplied name. (More consistent in line with other modules/ more convenient)

**Comment by JonRoma** [comment]
We might want to follow tactic used in other modules wherein we support either a name or ID. Lookup by name should be supported in any event.

**Comment by JonRoma** [comment]
This was implemented a very long time ago by #3.
